spring:
  profiles:
    active: core,db
  messages:
    encoding: UTF-8
  servlet:
    multipart:
      #是否启用http上传处理
      enabled: true
      #设置单个文件最大长度
      max-file-size: 10MB
      #最大请求文件的大小
      max-request-size: 100MB

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    com.example.tinymall:  DEBUG
server:
  port: 8090

image:
  path:
    prefix: http://localhost:8090/
